name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        targetplatform: [x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go Environment
        uses: actions/setup-go@v4

      - name: Prepare Release Version
        id: set_version
        shell: pwsh
        run: |
          $version = Get-Date -Format "yyyy.MM.dd"
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Build Binary
        run: |
          mkdir -p bin
          go build -o bin/gorillapkg.exe main.go

      - name: Package Binaries
        run: |
          mkdir -p release
          move bin/*.exe release/

      - name: Create GitHub Release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $env:RELEASE_VERSION release/*.exe `
            --title "GorillaPkg v$env:RELEASE_VERSION" `
            --notes "Automated release for version $env:RELEASE_VERSION."
