name: Build PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        targetplatform: [x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go Environment
        uses: actions/setup-go@v4

      - name: Build Binary
        run: |
          mkdir -p bin
          go build -o bin/gorillapkg.exe main.go

      - name: Verify Output
        run: |
          dir /s /b bin/*.exe
